import '@/app/styles/globals.css';
import '@/app/styles/fonts.css';

import { ChildProp } from '@/types/common';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: ChildProp) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
