name: Build Next.js Application

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_VERCEL_URL: ${{ secrets.NEXT_PUBLIC_VERCEL_URL }}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      SANITY_API_READ_TOKEN: ${{ secrets.SANITY_API_READ_TOKEN }}
      SKIP_ENV_VALIDATION: true

    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run Build
        run: npm run build
